services:
  postgres:
    image: postgres:17.0
    container_name: postgresdb
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data  # Data directory
      - /data/postgres/config:/etc/postgresql  # Configuration directory
      - /data/vmkidocker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - /data/vmkidocker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

